### ISSUE TITLE
[Feature request] Defender: Event on nickname change

### ISSUE THREAD

**Issue by jakjakob** [Twentysix26/x26-Cogs#79] opened 2023-12-05 17:28 UTC
**Cog**
- [x ] Defender

**Describe the feature you'd like to see**
Would be nice to have an event called on-nickname-change to better optimise nickname based rules (for example to remove unwanted nicknames etc)

**Comment by EternalllZM** [comment] 2023-12-18 14:09
Duplicate of https://github.com/Twentysix26/x26-Cogs/issues/59

**Comment by jakjakob** [comment] 2023-12-28 21:29
closing since duplicate

**Closed** 2023-12-28 21:29 UTC
Labels: enhancement
